- platform: group
  name: "Living lampen"
  entities:
   - light.grote_lamp_living
   - light.kleine_lamp_living
- platform: group
  name: "Zolder lampen"
  entities:
   - light.lamp_zolder_1_16
   - light.lamp_zolder_2_15

- platform: group
  name: "Gang lampen"
  entities:
   - light.lichten_gang_39

- platform: group
  name: "Alert lampen"
  entities:
   - light.licht_terras_30
   - light.kerstboom_35
