title: Huisje Bie Ben Mathijs en Willem
views:
  - title: Dashboard
    id: dashboard
    cards:     
      - type: markdown
        entity_id: sensor.garbage_collect
        content: >
          # Huisvuilophaling
          
          
          {{ states("sensor.garbage_collect") }}
          
      - type: weather-forecast
        entity: weather.thuis
      - camera_view: live
        type: picture-entity
        entity: camera.buienradar
      - type: entity-filter
        card:
          type: glance
          title: Lichten aan
        entities:
          - light.kleine_lamp_living
          - light.grote_lamp_living
          - light.kerstboom_35
          - light.lamp_eetplaats_25
          - light.lamp_kamer_mathijs_24
          - light.lamp_zolder_1_16
          - light.lamp_zolder_2_15
          - light.led_strip_keuken_26
          - light.licht_gang_beneden_10
          - light.licht_gang_boven_11
          - light.licht_terras_30
          - light.lichten_gang_39
          - light.lichten_keuken_29
          - light.maantje_zolder_13
        show_header_toggle: true
        state_filter:
          - "on"
        show_empty: false
      - type: entities
        show_header_toggle: false
        title: GSMs
        id: cellphones
        entities:
         - sensor.gsm_ben_battery_sensor_3
         - sensor.gsm_bie_battery_sensor
      - camera_view: live
        type: picture-entity
        entity: camera.ipcam_willem
      - camera_view: live
        type: picture-entity
        entity: camera.ipcam_mathijs
      - camera_view: live
        type: picture-entity
        entity: camera.ipcam_oprit_2        
        

  - title: Beneden
    id: downstairs
    cards:
      - type: entities
        title: Living
        id: downstairs_living
        entities:
         - binary_sensor.tv_downstairs
         - light.grote_lamp_living
         - light.kleine_lamp_living
         - sensor.living_temperature
         - sensor.living_air_quality
         - sensor.living_humidity
         - sensor.living_light_amount
         - sensor.living_noise
      - type: light
        entity: light.living_lampen
      - type: media-control
        entity: media_player.osmcliving
      - type: media-control
        entity: media_player.living
      - type: media-control
        entity: media_player.woonkamer
      - type: vertical-stack
        title: TV Versterker
        id: tv_amp
        cards:
         - type: horizontal-stack
           cards:
            - type: entities
              entities:
               - input_select.tv_amp_source
            - type: entity-button
              icon: mdi:volume-plus
              entity: script.tv_amp_volume_up_5
              tap_action:
                action: call-service
                service: script.turn_on
                service_data:
                  entity_id: script.tv_amp_volume_up_5
            - type: entity-button
              icon: mdi:volume-minus
              entity: script.tv_amp_volume_down_5
              tap_action:
                action: call-service
                service: script.turn_on
                service_data:
                  entity_id: script.tv_amp_volume_down_5

         - type: horizontal-stack
           cards:
            - type: entity-button
              entity: script.tv_amp_mute
              tap_action:
                action: call-service
                service: script.turn_on
                service_data:
                  entity_id: script.tv_amp_mute
              icon: mdi:volume-off
            - type: entity-button
              icon: mdi:volume-plus
              entity: script.tv_amp_volume_up_1
              tap_action:
                action: call-service
                service: script.turn_on
                service_data:
                  entity_id: script.tv_amp_volume_up_1

            - type: entity-button
              icon: mdi:volume-minus
              entity: script.tv_amp_volume_down_1
              tap_action:
                action: call-service
                service: script.turn_on
                service_data:
                  entity_id: script.tv_amp_volume_down_1

      - type: entities
        title: Bureau
        id: bureau
        entities:
         - light.licht_gang_beneden_10
      - type: entities
        show_header_toggle: false
        title: GSMs
        id: cellphones
        entities:
         - sensor.gsm_ben_battery_sensor_3
         - sensor.gsm_bie_battery_sensor
      - type: vertical-stack
        title: Keuken
        id: downstairs_keuken
        cards:
          - type: entities
            title: Keuken
            entities:
             - light.lichten_keuken_29
             - light.led_strip_keuken_26
             - light.lamp_eetplaats_25
             - light.kerstboom_35
             - binary_sensor.achterdeur         
          - type: horizontal-stack
            id: novy_hood
            title: Dampkap
            cards:
             - type: entity-button
               icon: mdi:fan
               entity: script.novy_hood_on
               tap_action:
                 action: call-service
                 service: script.turn_on
                 service_data:
                   entity_id: script.novy_hood_on
             - type: entity-button
               icon: mdi:fan-off
               entity: script.novy_hood_off
               tap_action:
                 action: call-service
                 service: script.turn_on
                 service_data:
                   entity_id: script.novy_hood_off
             - type: entity-button
               icon: mdi:car-parking-lights
               entity: script.novy_hood_lights
               tap_action:
                 action: call-service
                 service: script.turn_on
                 service_data:
                   entity_id: script.novy_hood_lights
             - type: entity-button
               icon: mdi:plus
               entity: script.novy_hood_plus
               tap_action:
                 action: call-service
                 service: script.turn_on
                 service_data:
                   entity_id: script.novy_hood_plus
             - type: entity-button
               icon: mdi:minus
               entity: script.novy_hood_minus
               tap_action:
                 action: call-service
                 service: script.turn_on
                 service_data:
                   entity_id: script.novy_hood_minus
             - type: entity-button
               icon: mdi:expand-all
               entity: script.novy_hood_max
               tap_action:
                 action: call-service
                 service: script.turn_on
                 service_data:
                   entity_id: script.novy_hood_max
          - type: media-control
            entity: media_player.squeeze_keuken

      - type: entities
        title: Kelder
        show_header_toggle: false
        id: downstairs_cave
        entities:
         - sensor.current_electricity_tariff
         - sensor.energiemeter_22
         - sensor.elektriciteitsverbruik_dag_peak
         - sensor.elektriciteitsverbruik_dag_offpeak
         - sensor.electricity_price_day
         - sensor.elektriciteitsverbruik_maand_peak
         - sensor.elektriciteitsverbruik_maand_offpeak
         - sensor.electricity_price_month
         - sensor.ups_kelder_battery_charge
#      - type: entities
#        title: Verwarming
#        id: heatingg
#        entities:
#          - input_select.thermostat_status
#          - sensor.desired_temperature
#          - sensor.heating_water_pressure
#          - sensor.burner
#          - sensor.hot_water_running
#          - sensor.temperature_heating_flow
#          - sensor.temperature_heating_return
      - type: entities
        title: Automaties
        show_header_toggle: false
        id: automations
        entities:
         - automation.everyone_gone
      - type: entities
        title: Gang
        id: downstairs_hallway
        entities:
         - light.lichten_gang_39
         - binary_sensor.voordeur

      - id: peoplehome
        type: entity-filter
        entities:
          - person.ben
          - person.bie
        state_filter:
          - 'home'
        card:
          type: glance
          title: Wie is er thuis?
    
  - title: Eerste verdieping
    id: firstfloor
    cards:
     - type: entities
       show_header_toggle: false
       title: Gang
       id: firstfloor_hallway
       entities:
        - light.lichten_gang_39
     - type: entities
       title: Slaapkamer Ben en Bie
       id: master_bedroom
       entities:
        - input_boolean.ben_sleeping
        - input_boolean.bie_sleeping
     - type: entities
       title: Slaapkamer Willem
       show_header_toggle: false
       id: bedroom_willem
       entities:
        - camera.ipcam_willem
        - light.lamp_kamer_mathijs_24
  - title: Tweede verdieping
    id: secondfloor
    cards:
     - type: entities
       title: Slaapkamer Mathijs
       id: bedroom_mathijs
       entities:
        - camera.ipcam_mathijs
        - light.lamp_zolder_1_16
        - light.lamp_zolder_2_15
        - light.maantje_zolder_13
     - type: light
       entity: light.zolder_lampen


  - title: Buiten
    id: outside
    cards:
      - type: markdown
        entity_id: sensor.garbage_collect
        content: >
          # Huisvuilophaling


          {{ states("sensor.garbage_collect") }}
      - type: weather-forecast
        entity: weather.thuis
      - id: peoplegone
        type: entity-filter
        entities:
          - person.ben
          - person.bie
        state_filter:
          - 'not_home'
        card:
          type: glance
          title: Wie is er weg van huis?

      - type: picture-entity
        entity: camera.buienradar
      - type: picture-entity
        entity: camera.ipcam_oprit_2
        

  - title: Cameras
    id: cameras
    cards:
     - camera_view: live
       type: picture-entity
       entity: camera.ipcam_willem
     - camera_view: live
       type: picture-entity
       entity: camera.ipcam_mathijs
     - camera_view: live
       type: picture-entity
       entity: camera.ipcam_oprit_2
  - title: LMS Controls
    cards:
      - type: vertical-stack
        cards:
          - type: entities
            title: LMS Player Controls
            show_header_toggle: false
            entities:
              - input_select.lms_player
              - input_select.lms_source
              - input_text.lms_artist
              - input_text.lms_album
              - input_text.lms_song
              - input_text.lms_playlist
              - input_select.lms_command
          - type: glance
            column_width: 33%
            show_state: false
            entities:
              - entity: script.lms_cmd_pause_player
                tap_action:
                  action: toggle
                name: Pause
              - entity: script.lms_cmd_start_player
                tap_action:
                  action: toggle
                name: Play
              - entity: script.lms_cmd_next_track
                tap_action:
                  action: toggle
                name: Next Track
          - type: glance
            column_width: 25%
            show_state: true
            entities:
              - input_number.lms_volume
              - input_number.lms_sleep_time
              - entity: input_boolean.lms_shuffle
                tap_action:
                  action: toggle
              - entity: input_boolean.lms_repeat
                tap_action:
                  action: toggle
      - type: entities
        title: LMS Sync Controls
        show_header_toggle: true
        entities:
          - input_select.lms_sync_master
          - input_boolean.lms_player1_sync
          - input_boolean.lms_player2_sync
          - input_boolean.lms_player3_sync
          - input_boolean.lms_player4_sync
          - input_boolean.lms_player5_sync
          - type: divider
          - input_text.lms_qry_result
          - type: divider
          - icon: 'mdi:cloud-check'
            name: LMS Controls - GitHub
            type: weblink
            url: 'https://github.com/ynot123/LMS_Controls'
      - type: glance
        title: Media Player Status
        column_width: 25%
        entities:
          - media_player.mediaroom
          - media_player.kitchen
          - media_player.garage
          - media_player.googlehome
          - media_player.googlemini_1
          - media_player.googlemini_2
          - media_player.familyroom
